//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_traiteur
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gestion_TraiteurEntities : DbContext
    {
        public Gestion_TraiteurEntities()
            : base("name=Gestion_TraiteurEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Commande> Commande { get; set; }
        public virtual DbSet<Etat> Etat { get; set; }
        public virtual DbSet<Evenement> Evenement { get; set; }
        public virtual DbSet<Objet> Objet { get; set; }
        public virtual DbSet<Repas> Repas { get; set; }
        public virtual DbSet<Reserver> Reserver { get; set; }
        public virtual DbSet<Traiteur> Traiteur { get; set; }
    }
}
