//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_traiteur
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserver
    {
        public int id_cmd { get; set; }
        public int id_O { get; set; }
        public Nullable<int> Nbr { get; set; }
    
        public virtual Commande Commande { get; set; }
        public virtual Objet Objet { get; set; }
    }
}
