//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_traiteur
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traiteur
    {
        public string Id { get; set; }
        public string admin_ { get; set; }
        public string Mdp_T { get; set; }
    }
}
